name: "infra"

services:
  filebeat:
    platform: linux/amd64
    image: docker.elastic.co/beats/filebeat:7.5.0
    container_name: filebeat
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/usr/share/dockerlogs/data:ro
    depends_on:
      - elasticsearch
      - logstash
    networks:
      - tejaswi-net

volumes:
  logstash-data:
    driver: local

networks:
  tejaswi-net:
    name: tejaswi-net
    driver: bridge
