name: 'infra'
services:

  grafana:
      image: grafana/grafana:latest
      container_name: grafana
      ports:
        - "3000:3000"
      depends_on:
        - prometheus
      volumes:
        - grafana-data:/var/lib/grafana
      environment:
        - GF_USERS_ALLOW_SIGN_UP=false

volumes:
  grafana-data:
    driver: local

networks:
  tejaswi-net:
    name: tejaswi-net
    driver: bridge