name: "infra"
services:
  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    platform: linux/amd64
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - tejaswi-net

volumes:
  elasticsearch-data:
    driver: local

networks:
  tejaswi-net:
    name: tejaswi-net
    driver: bridge
