name: 'infra'
services:
  mongodb:
    platform: linux/amd64
    container_name: mongodb
    image: 'mongo:latest'
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    networks:
      - tejaswi-net

volumes:
  db_data:
    driver: local  

networks:
  tejaswi-net:
    name: tejaswi-net
    driver: bridge