name: "infra"

services:
  kibana:
    platform: linux/amd64
    image: docker.elastic.co/kibana/kibana:7.5.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - tejaswi-net

volumes:
  logstash-data:
    driver: local

networks:
  tejaswi-net:
    name: tejaswi-net
    driver: bridge
