metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

metricbeat.modules:
  - module: elasticsearch
    metricsets:
      - ccr
      - cluster_stats
      - enrich
      - index
      - index_recovery
      - index_summary
      - ml_job
      - node_stats
      - shard
    xpack.enabled: true
    period: 10s
    hosts: http://elasticsearch:9200
    ssl.enabled: false

  - module: logstash
    metricsets: ["node", "node_stats"]
    xpack.enabled: true
    period: 10s
    hosts: http://logstash:9600

  - module: kibana
    metricsets:
      - stats
    period: 10s
    hosts: http://kibana:5601
    xpack.enabled: true

  - module: docker
    metricsets:
      - "container"
      - "cpu"
      - "diskio"
      - "healthcheck"
      - "info"
      #- "image"
      - "memory"
      - "network"
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enabled: true

processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: http://elasticsearch:9200
